### PR TITLE
Revert "T/290: Tests are executed as a single entry point"

### PR DESCRIPTION
**Pull request by pomek**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Revert: "T/290: Tests are executed as a single entry point" (https://github.com/ckeditor/ckeditor5-dev/commit/5fc685f).

### CODE REVIEW

**Comment by pomek** [comment]
image

**Comment by ma2ciek** [comment]
screen shot 2017-11-24 at 15 23 20

**Comment by pomek** [comment]
Ok, so I'm merging this.

**Comment by ma2ciek** [comment]
U mnie też zielono

**Pull request merged**
