### PR TITLE
Fix: compatiblity with extract-text-webpack-plugin. Closes #425

### LINKED ISSUE #425: MultipleLanguageTranslationService incompatible with extract-text-webpack-plugin
I can't compile custom build of ckeditor when using CKEditorWebpackPlugin together with ExtractTextPlugin (3.0.2). I also tried using an custom build with webpack4 and mini-css-extract-plugin and got the same error.

When i remove the "additionalLanguages" option from CKEditorWebpackPlugin it is working.

```
Webpack Error:
\ckeditor5-build-inline\node_modules\webpack-sources\lib\ConcatSource.js:23
                        return typeof item === "string" ? item : item.source();
                                                                     ^

TypeError: Cannot read property 'source' of undefined
    at C:\Git\selfserviceportal\Sources\App.Externals\ckeditor5-build-inline\node_modules\webpack-sources\lib\ConcatSource.js:23:49
    at Array.map (native)
    at ConcatSource.source (C:\Git\selfserviceportal\Sources\App.Externals\ckeditor5-build-inline\node_modules\webpack-sources\lib\ConcatSource.js:22:24)
    at writeOut (C:\Git\selfserviceportal\Sources\App.Externals\ckeditor5-build-inline\node_modules\webpack\lib\Compiler.js:331:27)
    at require.forEach (C:\Git\selfserviceportal\Sources\App.Externals\ckeditor5-build-inline\node_modules\webpack\lib\Compiler.js:345:12)
    at C:\Git\selfserviceportal\Sources\App.Externals\ckeditor5-build-inline\node_modules\async\dist\async.js:3110:16
    at eachOfArrayLike (C:\Git\selfserviceportal\Sources\App.Externals\ckeditor5-build-inline\node_modules\async\dist\async.js:1069:9)
    at eachOf (C:\Git\selfserviceportal\Sources\App.Externals\ckeditor5-build-inline\node_modules\async\dist\async.js:1117:5)
    at Object.eachLimit (C:\Git\selfserviceportal\Sources\App.Externals\ckeditor5-build-inline\node_modules\async\dist\async.js:3172:5)
    at emitFiles (C:\Git\selfserviceportal\Sources\App.Externals\ckeditor5-build-inline\node_modules\webpack\lib\Compiler.js:315:21)
    at C:\Git\selfserviceportal\Sources\App.Externals\ckeditor5-build-inline\node_modules\mkdirp\index.js:48:26
    at FSReqWrap.oncomplete (fs.js:123:15)
error Command failed with exit code 1.
```
I used the configuration example from the documentation: https://docs.ckeditor.com/ckeditor5/latest/builds/guides/integration/advanced-setup.html#option-extracting-css

```
Webpack Config:
/**
 * @license Copyright (c) 2003-2018, CKSource - Frederico Knabben. All rights reserved.
 * For licensing, see LICENSE.md.
 */

'use strict';

/* eslint-env node */

const path = require('path');
const webpack = require('webpack');
const { bundler, styles } = require('@ckeditor/ckeditor5-dev-utils');
const CKEditorWebpackPlugin = require('@ckeditor/ckeditor5-dev-webpack-plugin');
const BabiliPlugin = require('babel-minify-webpack-plugin');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const buildConfig = require('./build-config');

module.exports = {
	devtool: 'source-map',

	entry: path.resolve(__dirname, 'src', 'ckeditor.js'),

	output: {
		path: path.resolve(__dirname, 'build'),
		filename: 'ckeditor.js',
		libraryTarget: 'umd',
		libraryExport: 'default',
		library: buildConfig.moduleName
	},

	plugins: [
		new CKEditorWebpackPlugin({
			language: buildConfig.config.language,
			additionalLanguages: 'all'
		}),
		new BabiliPlugin(null, {
			comments: false
		}),
		new webpack.BannerPlugin({
			banner: bundler.getLicenseBanner(),
			raw: true
		}),
		new ExtractTextPlugin('ckeditor.css'),
		new webpack.optimize.ModuleConcatenationPlugin()
	],

	module: {
		rules: [
			{
				test: /\.svg$/,
				use: ['raw-loader']
			},
			{
				test: /\.css$/,
				use: ExtractTextPlugin.extract({
					fallback: 'style-loader',
					use: [
						{
							loader: 'postcss-loader',
							options: styles.getPostCssConfig({
								themeImporter: {
									themePath: require.resolve('@ckeditor/ckeditor5-theme-lark')
								},
								minify: true
							})
						}
					]
				})
			}
		]
	}
};
```

### PR DESCRIPTION
**Pull request by agentschmitt**
Fix: compatiblity with extract-text-webpack-plugin. Closes #425

---

### Additional information

When using extract-text-webpack-plugin the getAssets function is called multiple times and the compilationAssets contain extract-text-webpack-plugin-name instead of the ckeditor.js.
Only one call of getAssets contains the ckeditor.js.
So i changed getAssets to return translations only when a valid script file is in compilation assets.

### CODE REVIEW

**Comment by ma2ciek** [comment]
Could you add a simple test including a fake asset mentioned here: https://github.com/ckeditor/ckeditor5-dev/issues/425#issuecomment-403879737 for the code you have written?

**Comment by Reinmar** [comment]
@ma2ciek, Please remember that we need to have a clarity whether this change is needed on latest major of this plugin or on the previous major. AFAIU, that's not clear yet?

**Comment by ma2ciek** [comment]
It's needed for both major versions. We need to create two releases of `ckeditor5-dev-utils` (`9.0.2` and `10.0.1`), so the `ckeditor5-dev-webpack-plugin` will resolve them correctly for versions `5` and `6`.

**Comment by ma2ciek** [comment]
I can create the second branch from the `9.0.1` tag.

**Comment by Reinmar** [comment]
> I can create the second branch from the 9.0.1 tag.

Please do. I'll release both versions.

**Comment by agentschmitt** [comment]
I have added an test for the corner case of plugins hooked into compilation assets.
Wasn't able to run them locally with npm run test. But the travis-ci passed.

**Comment by ma2ciek** [comment]
It looks good :) I'll use your changes to create a branch for PR for the 9.0.x version.

**Comment by ma2ciek** [comment]
Merged :) And both versions will be released soon.

**Comment by Reinmar** [comment]
I've just published:

* `@ckeditor/ckeditor5-dev-utils@9.0.2` (for `@ckeditor/ckeditor5-dev-webpack-plugin@5.x.x`)
* `@ckeditor/ckeditor5-dev-utils@10.0.1` (for `@ckeditor/ckeditor5-dev-webpack-plugin@6.0.1`)

Thanks, @agentschmitt!

**Pull request merged**
