### PR TITLE
Improving doclet validator.

### LINKED ISSUE #507: The JSDoc validator improvements
Currently, all reference can be types too. And that's incorrect, references to interface members or typedef properties or events can't be used as types.

+ Check if the `@extends` tag points to the correct symbol.

### PR DESCRIPTION
**Pull request by ma2ciek**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Other: The doclet validator is improved. Now, during parameters linting it logs an error if the doclet cannot be a valid type (e.g. a method, property or a mixin cannot be a valid type). It also checks now whether the `@extends` tag points to the valid reference. Closes #507.

---

### Additional information

*For example – encountered issues, assumptions you had to make, other affected tickets, etc.*

### CODE REVIEW

**Comment by Reinmar** [comment]
@ma2ciek do you want to finish this? If not, I'll close this PR.

**Comment by ma2ciek** [comment]
I'll try to finish it within this iteration. Do you remember what else can be improved in the validator? I remember that you have had some ideas.

**Comment by Reinmar** [comment]
No, I didn't have any issues with it for a long time, so I forgot about this completely. But whatever we have, let's now merge that. It's an added value anyway.

**Comment by ma2ciek** [comment]
This PR comes with a bunch of new errors in the CKEditor 5 API docs building:

```
Incorrect param type: module:ui/template~RenderData#revertData
        at /Users/maciejbukowski/workspace/ckeditor5/packages/ckeditor5-ui/src/template.js:808

Incorrect param type: module:utils/emittermixin~EmitterMixin
        at /Users/maciejbukowski/workspace/ckeditor5/packages/ckeditor5-ui/src/viewcollection.js:164

Incorrect param type: module:utils/emittermixin~EmitterMixin
        at /Users/maciejbukowski/workspace/ckeditor5/packages/ckeditor5-utils/src/emittermixin.js:436

Incorrect param type: module:utils/emittermixin~EmitterMixin
        at /Users/maciejbukowski/workspace/ckeditor5/packages/ckeditor5-utils/src/emittermixin.js:453

Incorrect param type: module:utils/emittermixin~EmitterMixin
        at /Users/maciejbukowski/workspace/ckeditor5/packages/ckeditor5-utils/src/emittermixin.js:465

Incorrect param type: module:link/linkcommand~LinkCommand#manualDecorators
        at /Users/maciejbukowski/workspace/ckeditor5/packages/ckeditor5-link/src/ui/linkformview.js:264

Incorrect param type: module:link/linkcommand~LinkCommand#manualDecorators
        at /Users/maciejbukowski/workspace/ckeditor5/packages/ckeditor5-link/src/ui/linkformview.js:300

Invalid return type: module:utils/dom/position~Options#positions.
        at /Users/maciejbukowski/workspace/ckeditor5/packages/ckeditor5-editor-inline/src/inlineeditoruiview.js:174

Invalid return type: module:utils/emittermixin~EmitterMixin.
        at /Users/maciejbukowski/workspace/ckeditor5/packages/ckeditor5-utils/src/emittermixin.js:436

Invalid return type: module:engine/model/element.
        at /Users/maciejbukowski/workspace/ckeditor5/packages/ckeditor5-table/src/commands/mergecellcommand.js:120
```

From what I can see, all of these errors are correct (mixins or methods should not be used as parameter types). I'll create a few PRs in these packages.

**Comment by ma2ciek** [comment]
I've made fixes in the following branches:
* https://github.com/ckeditor/ckeditor5-editor-inline/tree/t/ckeditor5-dev/508
* https://github.com/ckeditor/ckeditor5-utils/tree/t/ckeditor5-dev/508
* https://github.com/ckeditor/ckeditor5-link/tree/t/ckeditor5-dev/508
* https://github.com/ckeditor/ckeditor5-ui/tree/t/ckeditor5-dev/508
* https://github.com/ckeditor/ckeditor5-table/tree/t/ckeditor5-dev/508
* https://github.com/ckeditor/ckeditor5-core/tree/t/ckeditor5-dev/508
* https://github.com/ckeditor/ckeditor5-engine/tree/t/ckeditor5-dev/508
* https://github.com/ckeditor/ckeditor5-enter/tree/t/ckeditor5-dev/508
* https://github.com/ckeditor/ckeditor5-image/tree/t/ckeditor5-dev/508
* https://github.com/ckeditor/ckeditor5-upload/tree/t/ckeditor5-dev/508
* https://github.com/ckeditor/ckeditor5-widget/tree/t/ckeditor5-dev/508

**Comment by Reinmar** [comment]
One possible followup – the below incorrect type still wasn't caught:

```
		 * @readonly
		 * @type {module:utils/dom/position~Options#positions}
		 */
		this.panelPositions = this._getPanelPositions();
```

The `@returns` annotation was verified, but this thing wasn't.

**Comment by Reinmar** [comment]
Opened a followup https://github.com/ckeditor/ckeditor5-dev/issues/549.

**Pull request merged**
