### PR TITLE
Provide support for plural forms i18n, make more generic tools

### PR DESCRIPTION
**Pull request by ma2ciek**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Feature: Provided support for plural forms i18n. Closes ckeditor/ckeditor5#6526. Closes https://github.com/ckeditor/ckeditor5/issues/988.

MINOR BREAKING CHANGE: Omitting the `language` property in the `CKEditorWebpackPlugin` will not have any effect from now. This means that in both cases only the main language (`language`) will be added to the main bundle and translations for other languages will be saved in separate files.
MAJOR BREAKING CHANGE: The translation process no longer creates short ids for message strings. From now, the source code will not be changed by the translation process, translations for the main language will be added to the bundle(s) and translations for other languages will be outputted to separate executable JS files.

---

### Additional information

The `t()` function accepts now a string or an object with the following properties:
- `string` (required)
- `id` - used to identify ambiguous translations
- `plural` - used when messages should support plural forms

This PR touches (but not resolves directly)
- https://github.com/ckeditor/ckeditor5/issues/1471
- https://github.com/ckeditor/ckeditor5/issues/763

*For example – encountered issues, assumptions you had to make, other affected tickets, etc.*

## Checklist

- [ ] CKEditor 5 manual tests work with new `CKEditorWebpackPlugin`
- [ ] CKEditor 5 builds work with various options of new `CKEditorWebpackPlugin`
- [ ] Integrations work with new `CKEditorWebpackPlugin`
- [ ] Docs update for the whole translation process
- [ ] Docs for the end-user
- [ ] Generating CKE5 docs

### CODE REVIEW

**Comment by ma2ciek** [comment]
I've found an issue with generating the `getPluralForm` function from the Tx rules for some languages. Debugging...

**Comment by mlewand** [comment]
Merged the `master` branch.

**Comment by mlewand** [comment]
Building the docs also throws an error:

```plaintext
Building 127 snippets...
Building snippets for language "en": 40% (building)[CKEditorWebpackPlugin] Error: No JS asset has been found during the compilation. You should add translation assets directly to the application from the 'lang' directory.
Building snippets for language "en": 89% (module assets processing)[CKEditorWebpackPlugin] Error: Too many JS assets has been found during the compilation. You should add translation assets directly to the application from the `lang` directory or use the `allowMultipleJSOutputs` option to add translations for the main language to all assets.
Build completed in 60.019s

Building snippets for language "multi-language": 20% (building)[CKEditorWebpackPlugin] Error: No JS asset has been found during the compilation. You should add translation assets directly to the application from the 'lang' directory.
Build co
```

**Comment by ma2ciek** [comment]
These warnings should be fixed now after merging ckeditor/ckeditor5#6654.

**Pull request merged**
