### PR TITLE
Allowed running automated and manual tests written in TS

### PR DESCRIPTION
**Pull request by oleq**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Feature (tests): Allowed running automated and manual tests written in TS. Closes ckeditor/ckeditor5#11888.

### CODE REVIEW

**Comment by pomek** [comment]
While I didn't have any issues running manual tests, I could not figure out how to enable automated tests.

Please, take a look at the attached errors:

```
ERROR in ./packages/ckeditor5-utils/tests/dom/iswindow.ts
Module build failed (from ./node_modules/ts-loader/index.js):
Error: TypeScript emitted no output for /Users/pomek/Projects/ckeditor/ckeditor5/packages/ckeditor5-utils/tests/dom/iswindow.ts.
    at makeSourceMapAndFinish (/Users/pomek/Projects/ckeditor/ckeditor5/node_modules/ts-loader/dist/index.js:52:18)
    at successLoader (/Users/pomek/Projects/ckeditor/ckeditor5/node_modules/ts-loader/dist/index.js:39:5)
    at Object.loader (/Users/pomek/Projects/ckeditor/ckeditor5/node_modules/ts-loader/dist/index.js:22:5)
 @ ./build/.automated-tests/entry-point.js 2:0-97

ERROR in /Users/pomek/Projects/ckeditor/ckeditor5/packages/ckeditor5-utils/tests/dom/iswindow.ts
14:2-8
[tsl] ERROR in /Users/pomek/Projects/ckeditor/ckeditor5/packages/ckeditor5-utils/tests/dom/iswindow.ts(14,3)
      TS2304: Cannot find name 'expect'.

ERROR in /Users/pomek/Projects/ckeditor/ckeditor5/packages/ckeditor5-utils/tests/dom/iswindow.ts
15:2-8
[tsl] ERROR in /Users/pomek/Projects/ckeditor/ckeditor5/packages/ckeditor5-utils/tests/dom/iswindow.ts(15,3)
      TS2304: Cannot find name 'expect'.

ERROR in /Users/pomek/Projects/ckeditor/ckeditor5/packages/ckeditor5-utils/tests/dom/iswindow.ts
16:2-8
[tsl] ERROR in /Users/pomek/Projects/ckeditor/ckeditor5/packages/ckeditor5-utils/tests/dom/iswindow.ts(16,3)
      TS2304: Cannot find name 'expect'.

ERROR in /Users/pomek/Projects/ckeditor/ckeditor5/packages/ckeditor5-utils/tests/dom/iswindow.ts
17:2-8
[tsl] ERROR in /Users/pomek/Projects/ckeditor/ckeditor5/packages/ckeditor5-utils/tests/dom/iswindow.ts(17,3)
      TS2304: Cannot find name 'expect'.

ERROR in /Users/pomek/Projects/ckeditor/ckeditor5/packages/ckeditor5-utils/tests/dom/iswindow.ts
18:2-8
[tsl] ERROR in /Users/pomek/Projects/ckeditor/ckeditor5/packages/ckeditor5-utils/tests/dom/iswindow.ts(18,3)
      TS2304: Cannot find name 'expect'.

ERROR in /Users/pomek/Projects/ckeditor/ckeditor5/packages/ckeditor5-utils/tests/dom/iswindow.ts
19:2-8
[tsl] ERROR in /Users/pomek/Projects/ckeditor/ckeditor5/packages/ckeditor5-utils/tests/dom/iswindow.ts(19,3)
      TS2304: Cannot find name 'expect'.

ERROR in /Users/pomek/Projects/ckeditor/ckeditor5/packages/ckeditor5-utils/tests/dom/iswindow.ts
29:2-8
[tsl] ERROR in /Users/pomek/Projects/ckeditor/ckeditor5/packages/ckeditor5-utils/tests/dom/iswindow.ts(29,3)
      TS2304: Cannot find name 'expect'.
```

I've tried to import `@types/mocha` in the generated entry-point file and directly in the test. Unfortunately, with no luck. Updating the `tsconfig.json` file with `types: [ ... ]` didn't help too.

Would you like to share any tips that might resolve my issues?

**Comment by pomek** [comment]
When compiling a manual test, `tsc` prints unrelated errors. It should not process automated tests.

image

**Comment by oleq** [comment]
🤔 This PR enables things on the webpack level. Bringing TS support for chai (and sinon, and... other libs) is another thing. But maybe you're right, maybe this PR got too broad at some wildcard.

**Comment by pomek** [comment]
Closing in favor of #886.

**Pull request closed without merging**
