### PR TITLE
Modified `engines` property to be removed by default in the release p…

### PR DESCRIPTION
**Pull request by martnpaneq**
…rocess.

### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Other (release-tools): Added support in the `cleanUpPackages()` task to provide a callback in the optional `packageJsonFieldsToRemove` option that allows specifying which fields to remove from the `package.json`. Closes ckeditor/ckeditor5#14586.

---

### Additional information

*For example – encountered issues, assumptions you had to make, other affected tickets, etc.*

### CODE REVIEW

**Review by pomek — COMMENTED** [review]
I am unsure about this change. Dipping this property in CKEditor 5 (mostly browser-side code) makes sense. However, in `ckeditor5-dev-*` packages, we should keep the minimal required Node version, as their code mostly runs in Node.

**Review by pomek — APPROVED** [review]
LGTM.

**Review by psmyrek — APPROVED** [review]
LGTM 🎉

**Comment by psmyrek** [comment]
I changed the commit message:
- This is not internal change, as it adds new minor feature in the public util.
- The previous description does not match the implementation.

**Pull request merged**
