### PR TITLE
T/172: Merge commits are ignored when releasing sub packages

### LINKED ISSUE #172: Merge commits are ignored when releasing sub packages
See https://github.com/ckeditor/ckeditor5-dev/pull/154#issuecomment-297476399.

### PR DESCRIPTION
**Pull request by pomek**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix:  Commits which changed files from a few packages will not be ignored now. `getChangedFilesForCommit()` returns a proper list of changed files for merge commits. Closes #172.

### CODE REVIEW

**Comment by Reinmar** [comment]
image

You sure something's changed?

**Comment by pomek** [comment]
Given commit (dcad502) is invalid so at this moment everything works as I expected.

**Comment by pomek** [comment]
By invalid I mean - there is no type of the commit. It will be delivered in the merge commit.

**Comment by Reinmar** [comment]
But why is the merge commit ignored? It's done after the last tag.

**Comment by Reinmar** [comment]
image

**Comment by pomek** [comment]
Ok, I introduced small fixes. Merge commit now is visible.

**Comment by Reinmar** [comment]
Something's still wrong.

image

And the second commit touched dev-env only:

https://github.com/ckeditor/ckeditor5-dev/commit/d56da51

**Comment by Reinmar** [comment]
For some reasons, `git log` returns more files:

```
(t/172 30c2b39) p@m /workspace/ckeditor5-dev> git log -m -1 --name-only --pretty="format:" d56da51
packages/ckeditor5-dev-env/lib/release-tools/utils/cli.js
packages/ckeditor5-dev-env/tests/release-tools/utils/cli.js

packages/ckeditor5-dev-bundler-rollup/package.json
packages/ckeditor5-dev-docs/package.json
packages/ckeditor5-dev-env/package.json
packages/ckeditor5-dev-tests/bin/install-dependencies.sh
packages/ckeditor5-dev-tests/lib/utils/automated-tests/getwebpackconfig.js
packages/ckeditor5-dev-tests/lib/utils/manual-tests/getwebpackconfig.js
packages/ckeditor5-dev-tests/package.json
packages/ckeditor5-dev-tests/tests/utils/automated-tests/getwebpackconfig.js
packages/ckeditor5-dev-utils/package.json
packages/ckeditor5-dev-webpack-plugin/package.json
packages/jsdoc-plugins/package.json
```

But we can see that they are separated from the first two. I don't know what that means.

**Comment by pomek** [comment]
> But we can see that they are separated from the first two. I don't know what that means.

http://stackoverflow.com/a/14717197/3388924

> There is some white space due to the merge having two parents but that can be easily removed.

Hmm… Can we assume the first part of the list is correct? I mean the part before an empty line.

**Comment by Reinmar** [comment]
> Hmm… Can we assume the first part of the list is correct? I mean the part before an empty line.

If we can verify that it's really it.

But I'd look for a safer solution. E.g.:

```
(master fefc1de) p@m /workspace/ckeditor5-dev> git diff --name-only d56da51~ d56da51
packages/ckeditor5-dev-env/lib/release-tools/utils/cli.js
packages/ckeditor5-dev-env/tests/release-tools/utils/cli.js
```

Unless there's something wrong with this one too.

**Comment by pomek** [comment]
Your solution looks ok. I will go this way. Thx.

**Comment by Reinmar** [comment]
Seems to work great:

image

**Comment by Reinmar** [comment]
Heh... except one thing:

image

The link in the header is to `v2.0.0...v5.0.0` while the previous version was v4.4.3.

Could you create a followup for this?

And do we have a followup for the missing new line before `### NOTE`?

**Comment by pomek** [comment]
> The link in the header is to v2.0.0...v5.0.0 while the previous version was v4.4.3.

For sub packages we have to pass other tags: `ckeditor5-dev-env@4.4.3..ckeditor5-dev-env@5.0.0`.

I will create a followup for it.

> And do we have a followup for the missing new line before ### NOTE?

Yes, we have (https://github.com/ckeditor/ckeditor5-dev/issues/146).

**Comment by pomek** [comment]
> Could you create a followup for this?

https://github.com/ckeditor/ckeditor5-dev/issues/175

**Comment by Reinmar** [comment]
Note: I merged it as "Internal" because it fixes a thing introduced in the same version. So it doesn't make sense to have both of them in the changelog.

**Pull request merged**
