### PR TITLE
T/290: Restored tests as a single entry point (Karma)

### LINKED ISSUE #290: Check if tests would work better if we had one entry point in Karma
Right now we tell Karma to load all our test files, which is something around ~200 entry points. This is a lot and makes Webpack compile editor 200 times – so when running `npm t` we load 200 entry points.

When we've been setting up Karma I noticed that some guys recommend to have just one entry point, generated on-the-fly. This entry point should simply import all the tests which should be loaded.

It's worth checking if this could help cause our 7000 tests can only be run reliably in Chrome and Safari (https://github.com/ckeditor/ckeditor5/issues/573).

### PR DESCRIPTION
**Pull request by pomek**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Feature: Restored previous Karma behavior. Tests will be compiled to a single entry point. Closes #290.

---

image

### CODE REVIEW

**Comment by szymonkups** [comment]
When running for example `npm t -- --files=core -c` there is no coverage report:
image
Also here coverage raport is empty:
image

**Comment by pomek** [comment]
f2fff73 should fix that.

image

Could you confirm?

**Comment by ma2ciek** [comment]
Not sure why, but Karma runs tests few times when the watch flag is turned on. E.g. try that: `npm run test -- --files utils -w`. It could be a separate issue connected with karma watcher.

**Comment by pomek** [comment]
But everything works fine when call `-c -w` :|

**Comment by ma2ciek** [comment]
`master` branch works as expected for me (runs tests only once).

> But everything works fine when call -c -w :|

**Comment by pomek** [comment]
I changed proposed solution. 

`getKarmaConfig()` should not create the entry file itself. I moved the logic a layer higher. 

Now, the entry file is creating before call the `getKarmaConfig()` function. The entry file won't be removed after tests execution. It is saved under path `build/.automated-tests/entry-point.js`.

Unfortunately, I'm still having some troubles with double tests execution in watch mode :/

I will report a ticket to Karma's devs but I need to prepare some setup that allows reproducing the issue easy way.

**Comment by Reinmar** [comment]
> Unfortunately, I'm still having some troubles with double tests execution in watch mode :/

That's an old issue. Not something introduced by these changes. And I think that you checked in the past that it's reported.

**Pull request merged**
