### PR TITLE
Support modern ECMAScript operators (coverage)

### PR DESCRIPTION
**Pull request by pomek**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix (tests): Support modern ECMAScript operators when checking the code coverage. Closes ckeditor/ckeditor5#13280.

### CODE REVIEW

**Comment by pomek** [comment]
image

image

---

image

image

**Comment by psmyrek** [comment]
I tried twice but it doesn't work for me. It hangs on "Webpack bundling".

Zrzut ekranu 2023-01-23 073355

This happens for any package with the `--coverage` flag.

**Review by psmyrek — APPROVED** [review]
I checked again, but this time without linking `ckeditor5-dev-tests` into `ckeditor5` repository. Instead, I did the following steps:
- I cloned `ckeditor5-dev-tests` inside the `external` folder - fix works fine ✅ 
- `npm pack` in `ckeditor5-dev-tests` and the installed the package in `ckeditor5` - fix works fine ✅

**Comment by niegowski** [comment]
I have one question. Will changes from this PR still work? https://github.com/ckeditor/ckeditor5-dev/pull/796/files

**Comment by pomek** [comment]
Good catch. Covered in https://github.com/ckeditor/ckeditor5-dev/commit/5b967048ec8769fcfd7de752a6f3e26870d282e6.

**Pull request merged**
