### PR TITLE
Cleanup after removed `ckeditor5-dev-env` and add missing exports for `web-crawler`, `transifex` and `release-tools`.

### PR DESCRIPTION
**Pull request by martnpaneq**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Internal: Cleanup after removed `ckeditor5-dev-env` and add missing exports for `web-crawler`, `transifex` and `release-tools`.

---

### Additional information

*For example – encountered issues, assumptions you had to make, other affected tickets, etc.*

### CODE REVIEW

**Comment by martnpaneq** [comment]
I was wondering if instead of exporting `ckeditor5-dev-web-crawler` internal functions and constants mabe it's a better idea to extract the cli function from `ckeditor5` package: https://github.com/ckeditor/ckeditor5/blob/master/scripts/web-crawler/index.js#L32

**Comment by pomek** [comment]
The [`parseArguments()`](https://github.com/ckeditor/ckeditor5/blob/master/scripts/web-crawler/index.js#L32-L59) without the `--docs` and `--manual` modifiers could be moved to `ckeditor5-dev-web-crawler` package. It should simplify the crawler integration itself in CKE 5.

**Comment by pomek** [comment]
> The [`parseArguments()`](https://github.com/ckeditor/ckeditor5/blob/master/scripts/web-crawler/index.js?rgh-link-date=2022-12-19T19%3A04%3A16Z#L32-L59) without the `--docs` and `--manual` modifiers could be moved to `ckeditor5-dev-web-crawler` package. It should simplify the crawler integration itself in CKE 5.

We agreed to abond the idea as it requires changes in both: CKE 5 and CKE 5 Dev.

**Comment by martnpaneq** [comment]
Turns out that it's not as easy to just move [parseArguments()](https://github.com/ckeditor/ckeditor5/blob/master/scripts/web-crawler/index.js#L32-L59) to `ckeditor5-dev-web-crawler`. It's used in `ckeditor5` and in `docs` and the implementations differ. So I think we should leave it as it is now.

**Pull request merged**
