### PR TITLE
[WIP] Enabled doclets generation out of typedef properties

### LINKED ISSUE #504: Cannot link to typedef's property - not found in JSDoc JSON data
Test case:

```js
/**
 * The mention feed descriptor. Used in {@link module:mention/mention~MentionConfig `config.mention`}.
 *
 * See {@link module:mention/mention~MentionConfig} to learn more.
 *
 *		{
 *			marker: '@',
 *			feed: [ 'Alice', 'Bob', ... ],
 *		}
 *
 * @typedef {Object} module:mention/mention~MentionFeed
 * @property {String} [marker='@'] The character which triggers auto-completion for mention.
 * @property {Array.<module:mention/mention~MentionFeedItem>|Function} feed The auto complete feed items. Provide an array for
 * static configuration or a function that returns a promise for asynchronous feeds.
 * @property {Number} [minimumCharacters=0] Specifies after how many characters show the autocomplete panel.
 * @property {Function} [itemRenderer] Function that renders {@link module:mention/mention~MentionFeedItem}
 * to the autocomplete list to a DOM element.
 */
```

And in other place I'd like to link to some property:

```js
/**
 * See the {@link module:mention/mention~MentionFeed#feed} for more!
 */
```

The generated API page for typedef looks OK:

Selection_251

but you cannot link to those properties and you get link validation errors.

### PR DESCRIPTION
**Pull request by ma2ciek**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Other: Enabled doclets generation out of typedef properties. Closes #504.

---

### Additional information

*For example – encountered issues, assumptions you had to make, other affected tickets, etc.*

### CODE REVIEW

**Comment by pomek** [comment]
Is it still WIP?

**Comment by ma2ciek** [comment]
@pomek, did you clarify if these changes are necessary for Umberto? Or can I close this PR?

**Comment by pomek** [comment]
We need those changes. I will merge it. I just need to check a few things in Umberto.

**Comment by Reinmar** [comment]
I looked at this PR today but since it has red tests I thought it's a WIP so I skipped it.

**Comment by pomek** [comment]
After fixing a failing test we can merge it.

**Comment by ma2ciek** [comment]
I've fixed the failing test. Once the CI is green it should be ready to review/merge.

**Comment by ma2ciek** [comment]
If it's important I can write tests in a follow-up as they are a little bit out of touch with reality.

**Pull request merged**
