### PR TITLE
T/282: Dependency Checker (imports from itself)

### LINKED ISSUE #282: Dependency Checker - note if package contains non-relative imports to itself
Follow-up of https://github.com/ckeditor/ckeditor5-dev/pull/279#discussion_r138374630.

### PR DESCRIPTION
**Pull request by pomek**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: Dependency Checker - non-relative links to itself will be caught. Closes #282.

### CODE REVIEW

**Comment by Reinmar** [comment]
Did you test it?

image

Neither is file name logged (dunno why in fact), nor is the error thrown at the end making sense for the message logged above.

**Comment by pomek** [comment]
It should work now. I didn't notice one variable… Sorry.

**Comment by Reinmar** [comment]
I **really** encourage you to read this error ;)

```
 #  @ckeditor/ckeditor5-ui                                                26/28 (93%)
========================================================================================================================

The files listed below should use relative paths to import modules from the package in which they are defined:

  - ./src/template.js

========================================================================================================================

/workspace/ckeditor5-dev/packages/ckeditor5-dev-tests/bin/check-dependencies.js:109
	throw new Error( 'Some of the files require dependencies which are not defined in "package.json".' );
	^

Error: Some of the files require dependencies which are not defined in "package.json".
    at Object.<anonymous> (/workspace/ckeditor5-dev/packages/ckeditor5-dev-tests/bin/check-dependencies.js:109:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

I mentioned two issues in my previous comment, but you fixed one.

**Comment by pomek** [comment]
Ok, I removed the `throw` keyword. We should use `process.exit()` to mark the script as invalid. Throwing error means "something with the code is invalid". In fact, the code is valid but the dependencies are missing and it is logged.

**Pull request merged**
