### PR TITLE
Make port number configurable for manual tests server.

### LINKED ISSUE #632: Cannot start manual tests server at different port.
Sometimes, I'd like to start the manual tests server at a port that is different than `8125`
- to run a test for multiple branches/clones,
- the port is occupied by another server/same server than hanged/didn't release the port.

PR is ready at https://github.com/ckeditor/ckeditor5-dev/pull/626

### PR DESCRIPTION
**Pull request by tomalec**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Feature: Make port number configurable for manual tests server. Closes #632.

---

### Additional information

It's useful when running multiple servers on the same machine, or when one server hangs for unknown reasons. I also added a test for starting the server without any params.

### CODE REVIEW

**Comment by Reinmar** [comment]
Can you also make a PR to ckeditor5 with changes to https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/testing-environment.html#running-manual-tests?

**Comment by tomalec** [comment]
PR for docs: https://github.com/ckeditor/ckeditor5/pull/6701

**Comment by tomalec** [comment]
> Coverage decreased (-1.8%) to 89.307% when pulling 7148eac on config-port into 24b718d on master.

Interesting. How have I decreased the test coverage, by adding tests to the untested file?

**Comment by tomalec** [comment]
If you're fine with those changes in general, I'll prepare a PR to "unhardcode" the port number for automated tests as well.

**Comment by ma2ciek** [comment]
> Interesting. How have I decreased the test coverage, by adding tests to the untested file?

I guess that the CC is generated only for files that were loaded during testing. So adding a test for a file that wasn't imported / tested before can decrease that percentage.

**Comment by tomalec** [comment]
So this PR effectively increased the real CC. I hope it means it could be merged as is, even if the exposed one decreased.

**Pull request merged**
