### PR TITLE
T/135 Fix problem with manual tests containing periods

### LINKED ISSUE #135: [TESTS] Manual test files cannot contain a period in name
My files structure looks like:

```
- ... 
- tests
 `- manual
   |- ckeditor.es6.html
   |- ckeditor.es6.js 
   `- ckeditor.es6.md
- ...
```

When I'm calling the `gulp test:manual`, it shows me an error:

image

I don't know why it searches for `ckeditor.md` instead of `ckeditor.es6.md`.

### PR DESCRIPTION
**Pull request by ma2ciek**
Fix: Manual tests containing period in file name should not crash. Closes #135.

### CODE REVIEW

**Comment by ma2ciek** [comment]
Misses test for now. But should work already.

**Comment by Reinmar** [comment]
I'd consider whether the `setExtension()` function is needed at all if it's used in just one place and whether this patch shouldn't fix that place too.

**Comment by ma2ciek** [comment]
```
 setExtension( mdFile, 'html' )
```

It's the only usage and here it'll work perfectly because the `setExtension` function removes the current extension and adds new extension. I can do it manually, but I'll need to parsing manually the path string. I can name it  `replaceExtension` to clarify the usage.

**Comment by pomek** [comment]
I would like to see a test which shows that the whole mechanism will work when files contain a period in their names. 

The test will provide that the bug (#135) will not appear once again.

**Comment by pomek** [comment]
To be more precise - I mean a file which has more than one a period in name, e.g. `ckeditor.test.js`.

**Comment by ma2ciek** [comment]
So I have already written it ;) https://github.com/ckeditor/ckeditor5-dev/blob/133aea73a86aeeb77f1b232e7f86a5e878272924/packages/ckeditor5-dev-tests/tests/utils/manual-tests/compilehtmlfiles.js#L114

**Comment by pomek** [comment]
Yea, I did not notice it. Sorry and thanks!

**Pull request merged**
