### PR TITLE
Add more tests for the translation scripts.

### PR DESCRIPTION
**Pull request by ma2ciek**
TODO: Two files still miss 100% CC.

### CODE REVIEW

**Comment by Reinmar** [comment]
2% more! :D

**Comment by Reinmar** [comment]
Ok, I see you added R- to the PR which I didn't notice before merging it. Feel free to add necessary improvements in a new PR.

**Comment by Reinmar** [comment]
And let me know when to close https://github.com/ckeditor/ckeditor5-dev/issues/156.

**Comment by ma2ciek** [comment]
Sure, I'll let you know :)

**Pull request merged**
