### PR TITLE
T/135 Fix problem with manual tests containing dots in file names

### PR DESCRIPTION
**Pull request by ma2ciek**
Fixes https://github.com/ckeditor/ckeditor5-dev/issues/135.

The glob pattern `globSync( path.join( sourceDir, '**', '*.!(js|html|md)' )` matches e.g. `someDir/ckeditor.es6.md`. It's hard for me to figure out the correct glob pattern for this match so I added the regexp exclusion.

### CODE REVIEW

**Comment by ma2ciek** [comment]
The Glob should be a superset of the RegExp. it would be much easier to figure out the correct pattern :)

**Comment by pomek** [comment]
Proposed changes are okay but would be nice to have a test which checks whether the files will be ignored. 

Because existing tests have been rewritten in #138, I propose to wait for #138 and then write the test.

**Comment by ma2ciek** [comment]
Yes, I agree. It's hard to test it because it's glob-dependent and unfortunately it could be tested well with fixtures only.

**Comment by Reinmar** [comment]
#138 was merged. So we're waiting here for a test?

**Comment by pomek** [comment]
Yes.

**Comment by ma2ciek** [comment]
I added the missing test.

**Pull request merged**
