### PR TITLE
Prevent validating inherited classes to get rid of warnings about invalid links.

### PR DESCRIPTION
**Pull request by martnpaneq**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Other (docs): Prevent validating inherited members to get rid of false positive warnings about invalid links. Closes ckeditor/ckeditor5#13298.

---

### Additional information

*For example – encountered issues, assumptions you had to make, other affected tickets, etc.*

### CODE REVIEW

**Review by pomek — COMMENTED** [review]
Please, rename test files to lower case.

**Comment by pomek** [comment]
Merge message: 

* Missing a scope.
* Missing "why".

**Review by pomek — APPROVED** [review]
LGTM.

**Review by psmyrek — APPROVED** [review]
LGTM 🎉 

I pushed small fix to hide one warning that is not important in the context of this PR.

```
warning Unable to find the "EventInfo" class.
```

**Comment by psmyrek** [comment]
I changed a bit the commit message to indicate that we are getting rid of **false positive** warnings.

**Pull request merged**
